// frontend/src/app/components/sorting-dropdown/sorting-dropdown.component.ts
import { Component } from '@angular/core';
import { WineStore } from '../../store/wine.store';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-sorting-dropdown',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './sorting-dropdown.component.html',
  styleUrl: './sorting-dropdown.component.css'
})
export class SortingDropdownComponent {
  constructor(public wineStore: WineStore) {}

  onSortChange(value: string) {
    this.wineStore.setSortBy(value);
  }
}

<div>
  <label for="sort-by" class="mr-2">Sort by:</label>
  <select
    id="sort-by"
    [ngModel]="wineStore.sortBy()"
    (ngModelChange)="onSortChange($event)"
    class="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
  >
    <option value="revenue">Revenue</option>
    <option value="bottles">Bottles Sold</option>
    <option value="orders">Number of Orders</option>
  </select>
</div>

// frontend/src/components/SortingDropdown.tsx
import React from 'react';

interface SortingDropdownProps {
  onSort: (sortBy: string) => void;
  currentSort: string;
}

export const SortingDropdown: React.FC<SortingDropdownProps> = ({ onSort, currentSort }) => {
  return (
    <div>
      <label htmlFor="sort-by" className="mr-2">Sort by:</label>
      <select
        id="sort-by"
        value={currentSort}
        onChange={(e) => onSort(e.target.value)}
        className="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
      >
        <option value="revenue">Revenue</option>
        <option value="bottles">Bottles Sold</option>
        <option value="orders">Number of Orders</option>
      </select>
    </div>
  );
};
