// frontend/src/components/WineList.tsx
import React from 'react';
import { Wine } from '../services/api';

interface WineListProps {
  wines: Wine[];
  totalCount: number;
  page: number;
  onPageChange: (page: number) => void;
}

export const WineList: React.FC<WineListProps> = ({ wines, totalCount, page, onPageChange }) => {
  const getRowClassName = (wine: Wine) => {
    if (wine.isTopTen) return 'bg-green-100';
    if (wine.isBottomTen) return 'bg-red-100';
    return '';
  };

  return (
    <div>
      <table className="min-w-full">
        <thead>
          <tr>
            <th className="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
              Rank
            </th>
            <th className="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
              Name
            </th>
            <th className="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
              Vintage
            </th>
            <th className="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
              Revenue
            </th>
            <th className="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
              Bottles Sold
            </th>
            <th className="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
              Orders
            </th>
          </tr>
        </thead>
        <tbody>
          {wines.map((wine) => (
            <tr key={wine.id} className={getRowClassName(wine)}>
              <td className="px-6 py-4 whitespace-nowrap">{wine.ranking}</td>
              <td className="px-6 py-4 whitespace-nowrap">{wine.name}</td>
              <td className="px-6 py-4 whitespace-nowrap">{wine.vintage}</td>
              <td className="px-6 py-4 whitespace-nowrap">${wine.total_revenue.toFixed(2)}</td>
              <td className="px-6 py-4 whitespace-nowrap">{wine.total_bottles}</td>
              <td className="px-6 py-4 whitespace-nowrap">{wine.total_orders}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="mt-4 flex justify-between">
        <button
          onClick={() => onPageChange(page - 1)}
          disabled={page === 1}
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
        >
          Previous
        </button>
        <span>Page {page} of {Math.ceil(totalCount / 20)}</span>
        <button
          onClick={() => onPageChange(page + 1)}
          disabled={page >= Math.ceil(totalCount / 20)}
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
        >
          Next
        </button>
      </div>
    </div>
  );
};

// frontend/src/app/components/wine-list/wine-list.component.ts
import { Component } from '@angular/core';
import { WineStore } from '../../store/wine.store';
import { CommonModule } from '@angular/common';
import { Wine } from '../../models/wine.model';

@Component({
  selector: 'app-wine-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './wine-list.component.html',
  styleUrl: './wine-list.component.css',
})
export class WineListComponent {
  headers = ['Rank', 'Name', 'Vintage', 'Revenue', 'Bottles Sold', 'Orders'];

  constructor(private wineStore: WineStore) {}

  getRowClassName(wine: any): string {
    if (wine.isTopTen) return 'bg-green-300';
    if (wine.isBottomTen) return 'bg-red-300';
    return '';
  }

  wines(): Wine[] {
    return this.wineStore.wines();
  }

  currentPage(): number {
    return this.wineStore.currentPage();
  }

  totalPages(): number {
    return this.wineStore.totalPages();
  }

  previousPage(): void {
    this.wineStore.previousPage();
  }

  nextPage(): void {
    this.wineStore.nextPage();
  }
}

<div>
  <table class="min-w-full">
    <thead>
      <tr>
        <th
          *ngFor="let header of headers"
          class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider"
        >
          {{ header }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr
        *ngFor="let wine of wines()"
        [ngClass]="getRowClassName(wine)"
      >
        <td class="px-6 py-4 whitespace-nowrap">{{ wine.ranking }}</td>
        <td class="px-6 py-4 whitespace-nowrap">{{ wine.name }}</td>
        <td class="px-6 py-4 whitespace-nowrap">{{ wine.vintage }}</td>
        <td class="px-6 py-4 whitespace-nowrap">
          ${{ wine.total_revenue.toFixed(2) }}
        </td>
        <td class="px-6 py-4 whitespace-nowrap">{{ wine.total_bottles }}</td>
        <td class="px-6 py-4 whitespace-nowrap">{{ wine.total_orders }}</td>
      </tr>
    </tbody>
  </table>
  <div class="mt-4 flex justify-between">
    <button
      (click)="previousPage()"
      [disabled]="currentPage() === 1"
      class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
    >
      Previous
    </button>
    <span>
      Page {{ currentPage() }} of {{ totalPages() }}
    </span>
    <button
      (click)="nextPage()"
      [disabled]="currentPage() === totalPages()"
      class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
    >
      Next
    </button>
  </div>
</div>
